apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: chat-app
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ29hZG1pbg== #mongoadmin
  MONGO_INITDB_ROOT_PASSWORD: c2VjcmV0 #secret
